{
 "title": "Just Ping, Enhanced",
 "tags": [
  "monitoring",
  "network",
  "ping",
  "http"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_dns_query_succeeded{instance=\"192.168.254.11\"}",
     "legendFormat": "pihole"
    },
    {
     "expr": "probe_dns_query_succeeded{instance=\"home.jomby.xyz\"}",
     "legendFormat": "home.jomby.xyz"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "network:external_health_score", "legendFormat": "external health" },
    { "expr": "network:local_health_score", "legendFormat": "local health" },
    { "expr": "network:overall_health_score", "legendFormat": "overall health" }
   ]
  },
  {
   "title": "Current Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_success", "legendFormat": "{{instance}} - {{job}}" }
   ]
  },
  {
   "title": "Ping Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox\"}",
     "legendFormat": "{{instance}} (ICMP Ping)"
    }
   ]
  },
  {
   "title": "Ping Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{job=\"blackbox\"} * 1000",
     "legendFormat": "{{instance}} (ICMP Ping)"
    }
   ]
  },
  {
   "title": "DNS Lookup Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "probe_dns_lookup_time_seconds", "legendFormat": "{{instance}} (DNS Lookup)" }
   ]
  },
  {
   "title": "Network Reliability (5-minute average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{job=\"blackbox\"}[5m])",
     "legendFormat": "{{instance}} (5m avg)"
    }
   ]
  }
 ]
}