{
 "title": "Ping",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Reliability",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "probe_success", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Probe success",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "probe_success", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ICMP duration seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "probe_icmp_duration_seconds", "legendFormat": "{{phase}}" }
   ]
  },
  {
   "title": "DNS lookup time seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "probe_dns_lookup_time_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Probe duration seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "probe_duration_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Reply hop limit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    { "expr": "probe_icmp_reply_hop_limit", "legendFormat": "__auto" }
   ]
  }
 ]
}